kind: pipeline
name: default

concurrency:
  limit: 1

clone:
  depth: 5

steps:
- name: test
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
  - make test	
  - make build

volumes:
- name: deps
  host:
    path: /var/lib/cache
